---
swagger: "2.0"
info:
  title: "shmenkins-webhook"
basePath: "/events"
schemes:
- "https"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /:
    post:
      responses:
        201:
          schema:
            $ref: "#/definitions/Empty"
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: 201
          500.*:
            statusCode: 500
        uri: "arn:aws:apigateway:{{ aws_region }}:lambda:path/2015-03-31/functions/arn:aws:lambda:{{ aws_region }}:{{ aws_account }}:function:handle_webhook/invocations"
        passthroughBehavior: "when_no_templates"
        httpMethod: "POST"
        type: "aws"
definitions:
  Empty:
    type: "object"
